// ============================================================
//  Car2Buy — sync USED-car inventory (יד 2) from the Google Sheet
//  into used-cars.json (committed to the repo). Run by GitHub Actions
//  on a schedule so the site auto-updates when the Sheet changes —
//  including the "תמונת הרכב 1/2/3" photo columns.
//  Only cars with status "למכירה" are published.
// ============================================================
import { writeFileSync, readFileSync } from 'node:fs';

const SHEET_ID = '1NkUkp2fc33Bt64MjOmo3PSts0oTf4Cs5DFD4ALQhVJE';
const CSV_URL = `https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:csv`;
// synchronous JS (like loan-cars.js) so pages get USED before render — no fetch/re-render needed
const OUT = new URL('../used-cars.js', import.meta.url);

// CSV Hebrew brand -> [display (English), logo slug]
const BR = {
  'ב מ וו': ['BMW', 'bmw'], "צ'רי": ['Chery', 'chery'], 'מרצדס': ['Mercedes', 'mercedes-benz'],
  "אם. ג'י. / MG": ['MG', 'mg'], 'יונדאי': ['Hyundai', 'hyundai'], 'בי ווי די': ['BYD', 'byd'],
  "פיג'ו": ['Peugeot', 'peugeot'], 'טסלה': ['Tesla', 'tesla'], 'סיאט': ['SEAT', 'seat'],
  'ניסאן': ['Nissan', 'nissan'], 'שברולט': ['Chevrolet', 'chevrolet'], 'מיצובישי': ['Mitsubishi', 'mitsubishi'],
  'סקודה': ['Skoda', 'skoda'], 'טויוטה': ['Toyota', 'toyota'], 'אאודי': ['Audi', 'audi'], 'קיה': ['Kia', 'kia'],
  'לינק אנד קו': ['Lynk & Co', 'lynk-co'], 'איסוזו': ['Isuzu', 'isuzu'], 'רנו': ['Renault', 'renault'],
  "גי'פ / Jeep": ['Jeep', 'jeep'], 'פולקסווגן': ['Volkswagen', 'volkswagen'], 'סיטרואן': ['Citroen', 'citroen'],
  "ג'יי.איי.סי / JAC": ['JAC', 'jac'], 'אקספנג / XPENG': ['Xpeng', 'xpeng'], 'סוזוקי': ['Suzuki', 'suzuki'], 'וולוו': ['Volvo', 'volvo']
};
const SUV = /X\d|טיגו|tiggo|טוסון|tucson|atto|אטו|gle|glc|q5|q3|q7|q8|x-?trail|אקס.?טרייל|2008|3008|5008|kona|קונה|ehs|\bhs\b|outlander|אאוטלנדר|santa|סנטה|kodiaq|קודיאק|karoq|קארוק|rav4|cx-?\d|kamiq|kicks|קיקס|juke|טוארג|touareg|tiguan|טיגואן|sportage|ספורטג|sorento|creta|קרטה|venue|nx\b|קרוסאובר|arona|ateca|pajero|eclipse|seal.?u|song|g6|g9|d-?max|דימקס|קרוס|cross|jimny|ויטרה|vitara|קורולה קרוס|ix\b|טרייל|kuga|escape|tucson/i;
const COUPE = /coupe|קופה|gran coupe|\b4-?series\b|סדרה 4/i;

function parseCSV(t) {
  const rows = []; let row = [], cur = '', q = false;
  for (let i = 0; i < t.length; i++) {
    const c = t[i];
    if (q) { if (c === '"') { if (t[i + 1] === '"') { cur += '"'; i++; } else q = false; } else cur += c; }
    else { if (c === '"') q = true; else if (c === ',') { row.push(cur); cur = ''; } else if (c === '\n') { row.push(cur); rows.push(row); row = []; cur = ''; } else if (c !== '\r') cur += c; }
  }
  if (cur || row.length) { row.push(cur); rows.push(row); }
  return rows;
}
const num = (s) => { const n = parseInt(String(s || '').replace(/[^\d.]/g, ''), 10); return isNaN(n) ? 0 : n; };
const fixBrand = (s) => { s = String(s || '').replace(/&#0?39;/g, "'").trim(); return BR[s] || [s, '']; };
const fuel = (s) => { s = (s || '').trim(); if (s === 'חשמלי') return 'חשמלי'; if (s === 'בנזין וחשמלי') return 'היברידי'; if (s === 'דיזל') return 'דיזל'; return 'בנזין'; };
const cleanUrl = (u) => { u = String(u || '').trim(); return /^https?:\/\//i.test(u) ? u : ''; };

const res = await fetch(CSV_URL, { redirect: 'follow' });
if (!res.ok) { console.error('sheet fetch failed', res.status); process.exit(1); }
const rows = parseCSV(await res.text());
const data = rows.slice(1).filter((r) => r[1] && r[1].trim());

const cars = data.filter((r) => (r[13] || '').trim() === 'למכירה').map((r) => {
  const [brand, slug] = fixBrand(r[1]);
  const model = (r[2] || '').trim();
  const trim = (r[3] || '').trim();
  const price = num(r[11]) || num(r[12]) || num(r[10]);
  const ft = fuel(r[5]);
  const hay = model + ' ' + trim;
  const gallery = [r[15], r[16], r[17]].map(cleanUrl).filter(Boolean);
  return {
    brand, name: model, trim,
    year: num(r[7]), km: num(r[6]), hand: num(r[8]) || 1,
    price, monthly: price ? Math.max(300, Math.round(price * 0.0116 / 10) * 10) : 0,
    cat: ft === 'חשמלי' ? 'ev' : COUPE.test(hay) ? 'sport' : SUV.test(hay) ? 'suv' : 'sedan',
    type: ft, color: (r[9] || '').trim(), plate: (r[4] || '').trim(), slug,
    img: gallery[0] || '', gallery
  };
});
cars.sort((a, b) => b.year - a.year || b.price - a.price);

const out = '/* AUTO-GENERATED by scripts/sync-used.mjs from the יד 2 Google Sheet. Do not edit by hand. */\n' +
  'window.Car2Buy = window.Car2Buy || {};\n' +
  'window.Car2Buy.USED = ' + JSON.stringify(cars, null, 0) + ';\n';
let prev = '';
try { prev = readFileSync(OUT, 'utf8'); } catch {}
if (prev.trim() === out.trim()) { console.log('no change (' + cars.length + ' used cars)'); process.exit(0); }
writeFileSync(OUT, out);
console.log('wrote used-cars.js —', cars.length, 'used cars');
